// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetCoreGraphQlLearn.Database;

#nullable disable

namespace NetCoreGraphQlLearn.Migrations
{
    [DbContext(typeof(AppDb))]
    [Migration("20230430150922_InitMig")]
    partial class InitMig
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("NetCoreGraphQlLearn.Models.League", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("flagLink")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Leagues");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Kutch, Hayes and Metz",
                            flagLink = "http://jarrett.net"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Stanton and Sons",
                            flagLink = "https://helene.info"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Kovacek LLC",
                            flagLink = "http://darius.com"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Bauch Inc",
                            flagLink = "http://darron.com"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Okuneva LLC",
                            flagLink = "http://aimee.name"
                        });
                });

            modelBuilder.Entity("NetCoreGraphQlLearn.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AnnualSalary")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TeamId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 24,
                            AnnualSalary = 73540.95m,
                            Name = "Sophia Cassin",
                            TeamId = 6
                        },
                        new
                        {
                            Id = 2,
                            Age = 28,
                            AnnualSalary = 121965.91m,
                            Name = "Carlee Morissette",
                            TeamId = 2
                        },
                        new
                        {
                            Id = 3,
                            Age = 21,
                            AnnualSalary = 418596.19m,
                            Name = "Gerardo Johns",
                            TeamId = 3
                        },
                        new
                        {
                            Id = 4,
                            Age = 27,
                            AnnualSalary = 567125.12m,
                            Name = "Vena Luettgen",
                            TeamId = 4
                        },
                        new
                        {
                            Id = 5,
                            Age = 40,
                            AnnualSalary = 270691.23m,
                            Name = "Hector Hahn",
                            TeamId = 7
                        },
                        new
                        {
                            Id = 6,
                            Age = 22,
                            AnnualSalary = 190196.40m,
                            Name = "Mariano Effertz",
                            TeamId = 2
                        },
                        new
                        {
                            Id = 7,
                            Age = 23,
                            AnnualSalary = 919829.73m,
                            Name = "Magnolia Lubowitz",
                            TeamId = 8
                        },
                        new
                        {
                            Id = 8,
                            Age = 30,
                            AnnualSalary = 867166.35m,
                            Name = "Tiara Predovic",
                            TeamId = 3
                        },
                        new
                        {
                            Id = 9,
                            Age = 35,
                            AnnualSalary = 774069.29m,
                            Name = "Colten Schroeder",
                            TeamId = 6
                        },
                        new
                        {
                            Id = 10,
                            Age = 32,
                            AnnualSalary = 553300.94m,
                            Name = "Savannah Bins",
                            TeamId = 3
                        },
                        new
                        {
                            Id = 11,
                            Age = 28,
                            AnnualSalary = 513907.46m,
                            Name = "Jeramie Marvin",
                            TeamId = 5
                        },
                        new
                        {
                            Id = 12,
                            Age = 19,
                            AnnualSalary = 958723.21m,
                            Name = "Antonetta Johnston",
                            TeamId = 4
                        },
                        new
                        {
                            Id = 13,
                            Age = 32,
                            AnnualSalary = 228698.82m,
                            Name = "Mekhi Cole",
                            TeamId = 2
                        },
                        new
                        {
                            Id = 14,
                            Age = 37,
                            AnnualSalary = 127326.93m,
                            Name = "Joana Koepp",
                            TeamId = 7
                        },
                        new
                        {
                            Id = 15,
                            Age = 36,
                            AnnualSalary = 628530.36m,
                            Name = "Gene Hermiston",
                            TeamId = 2
                        },
                        new
                        {
                            Id = 16,
                            Age = 20,
                            AnnualSalary = 783258.47m,
                            Name = "Logan Torphy",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 17,
                            Age = 28,
                            AnnualSalary = 158508.92m,
                            Name = "Sierra Watsica",
                            TeamId = 7
                        },
                        new
                        {
                            Id = 18,
                            Age = 26,
                            AnnualSalary = 58139.17m,
                            Name = "Rachelle Berge",
                            TeamId = 4
                        },
                        new
                        {
                            Id = 19,
                            Age = 35,
                            AnnualSalary = 901115.46m,
                            Name = "Myrtle Ziemann",
                            TeamId = 10
                        },
                        new
                        {
                            Id = 20,
                            Age = 39,
                            AnnualSalary = 251105.58m,
                            Name = "Eldred Keeling",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 21,
                            Age = 25,
                            AnnualSalary = 962691.25m,
                            Name = "Holden Senger",
                            TeamId = 3
                        },
                        new
                        {
                            Id = 22,
                            Age = 21,
                            AnnualSalary = 95573.20m,
                            Name = "Garrison Yost",
                            TeamId = 2
                        },
                        new
                        {
                            Id = 23,
                            Age = 22,
                            AnnualSalary = 220896.02m,
                            Name = "Mossie Effertz",
                            TeamId = 3
                        },
                        new
                        {
                            Id = 24,
                            Age = 22,
                            AnnualSalary = 212728.58m,
                            Name = "Barton Wisozk",
                            TeamId = 8
                        },
                        new
                        {
                            Id = 25,
                            Age = 20,
                            AnnualSalary = 198501.62m,
                            Name = "Murphy Pacocha",
                            TeamId = 5
                        },
                        new
                        {
                            Id = 26,
                            Age = 36,
                            AnnualSalary = 522147.58m,
                            Name = "Wilford Kshlerin",
                            TeamId = 8
                        },
                        new
                        {
                            Id = 27,
                            Age = 31,
                            AnnualSalary = 794055.84m,
                            Name = "Beau Sporer",
                            TeamId = 6
                        },
                        new
                        {
                            Id = 28,
                            Age = 33,
                            AnnualSalary = 939589.28m,
                            Name = "Kamren Swaniawski",
                            TeamId = 9
                        },
                        new
                        {
                            Id = 29,
                            Age = 29,
                            AnnualSalary = 118271.81m,
                            Name = "Brayan Welch",
                            TeamId = 7
                        },
                        new
                        {
                            Id = 30,
                            Age = 25,
                            AnnualSalary = 252443.42m,
                            Name = "Donato Fadel",
                            TeamId = 5
                        },
                        new
                        {
                            Id = 31,
                            Age = 33,
                            AnnualSalary = 156770.07m,
                            Name = "Ezekiel Hudson",
                            TeamId = 8
                        },
                        new
                        {
                            Id = 32,
                            Age = 33,
                            AnnualSalary = 689878.64m,
                            Name = "Griffin Boehm",
                            TeamId = 4
                        },
                        new
                        {
                            Id = 33,
                            Age = 39,
                            AnnualSalary = 800446.20m,
                            Name = "Jessika Ebert",
                            TeamId = 9
                        },
                        new
                        {
                            Id = 34,
                            Age = 30,
                            AnnualSalary = 773643.07m,
                            Name = "Vivian Bode",
                            TeamId = 9
                        },
                        new
                        {
                            Id = 35,
                            Age = 21,
                            AnnualSalary = 149748.99m,
                            Name = "Joanne Huel",
                            TeamId = 8
                        },
                        new
                        {
                            Id = 36,
                            Age = 26,
                            AnnualSalary = 881432.01m,
                            Name = "Salma Bernier",
                            TeamId = 7
                        },
                        new
                        {
                            Id = 37,
                            Age = 26,
                            AnnualSalary = 426518.02m,
                            Name = "Keeley Wunsch",
                            TeamId = 6
                        },
                        new
                        {
                            Id = 38,
                            Age = 34,
                            AnnualSalary = 943471.32m,
                            Name = "Vern Marks",
                            TeamId = 4
                        },
                        new
                        {
                            Id = 39,
                            Age = 36,
                            AnnualSalary = 537575.89m,
                            Name = "Zoey Marvin",
                            TeamId = 9
                        },
                        new
                        {
                            Id = 40,
                            Age = 38,
                            AnnualSalary = 566427.62m,
                            Name = "Anibal Doyle",
                            TeamId = 9
                        },
                        new
                        {
                            Id = 41,
                            Age = 28,
                            AnnualSalary = 306359.63m,
                            Name = "Billie Schulist",
                            TeamId = 10
                        },
                        new
                        {
                            Id = 42,
                            Age = 37,
                            AnnualSalary = 843862.56m,
                            Name = "Lavinia Stroman",
                            TeamId = 10
                        },
                        new
                        {
                            Id = 43,
                            Age = 34,
                            AnnualSalary = 593265.53m,
                            Name = "Sydni Beahan",
                            TeamId = 7
                        },
                        new
                        {
                            Id = 44,
                            Age = 31,
                            AnnualSalary = 218681.29m,
                            Name = "Destiny Heaney",
                            TeamId = 7
                        },
                        new
                        {
                            Id = 45,
                            Age = 39,
                            AnnualSalary = 451748.05m,
                            Name = "Erika Jenkins",
                            TeamId = 8
                        },
                        new
                        {
                            Id = 46,
                            Age = 30,
                            AnnualSalary = 252901.79m,
                            Name = "Kathlyn Marks",
                            TeamId = 3
                        },
                        new
                        {
                            Id = 47,
                            Age = 24,
                            AnnualSalary = 872700.83m,
                            Name = "Leone Bradtke",
                            TeamId = 6
                        },
                        new
                        {
                            Id = 48,
                            Age = 30,
                            AnnualSalary = 697799.05m,
                            Name = "Margie Ebert",
                            TeamId = 6
                        },
                        new
                        {
                            Id = 49,
                            Age = 26,
                            AnnualSalary = 812423.97m,
                            Name = "Horacio Daniel",
                            TeamId = 6
                        },
                        new
                        {
                            Id = 50,
                            Age = 37,
                            AnnualSalary = 186511.82m,
                            Name = "Camryn O'Hara",
                            TeamId = 2
                        },
                        new
                        {
                            Id = 51,
                            Age = 18,
                            AnnualSalary = 413730.00m,
                            Name = "Brionna Schulist",
                            TeamId = 4
                        },
                        new
                        {
                            Id = 52,
                            Age = 27,
                            AnnualSalary = 712844.56m,
                            Name = "Anabel Becker",
                            TeamId = 2
                        },
                        new
                        {
                            Id = 53,
                            Age = 33,
                            AnnualSalary = 653803.22m,
                            Name = "Taurean Jast",
                            TeamId = 3
                        },
                        new
                        {
                            Id = 54,
                            Age = 19,
                            AnnualSalary = 365843.54m,
                            Name = "Madge Kunde",
                            TeamId = 9
                        },
                        new
                        {
                            Id = 55,
                            Age = 21,
                            AnnualSalary = 13660.74m,
                            Name = "Heath Legros",
                            TeamId = 6
                        },
                        new
                        {
                            Id = 56,
                            Age = 21,
                            AnnualSalary = 277784.26m,
                            Name = "Yoshiko Bartell",
                            TeamId = 5
                        },
                        new
                        {
                            Id = 57,
                            Age = 23,
                            AnnualSalary = 951695.17m,
                            Name = "Carmelo Fadel",
                            TeamId = 5
                        },
                        new
                        {
                            Id = 58,
                            Age = 18,
                            AnnualSalary = 750226.79m,
                            Name = "Pinkie Hane",
                            TeamId = 4
                        },
                        new
                        {
                            Id = 59,
                            Age = 37,
                            AnnualSalary = 656529.38m,
                            Name = "Junior Erdman",
                            TeamId = 2
                        },
                        new
                        {
                            Id = 60,
                            Age = 38,
                            AnnualSalary = 211102.80m,
                            Name = "Mara Strosin",
                            TeamId = 8
                        },
                        new
                        {
                            Id = 61,
                            Age = 26,
                            AnnualSalary = 861849.91m,
                            Name = "Carey Harris",
                            TeamId = 2
                        },
                        new
                        {
                            Id = 62,
                            Age = 27,
                            AnnualSalary = 946046.40m,
                            Name = "Murl Collins",
                            TeamId = 2
                        },
                        new
                        {
                            Id = 63,
                            Age = 18,
                            AnnualSalary = 491822.41m,
                            Name = "Germaine Lang",
                            TeamId = 6
                        },
                        new
                        {
                            Id = 64,
                            Age = 25,
                            AnnualSalary = 197290.73m,
                            Name = "Jamar Green",
                            TeamId = 3
                        },
                        new
                        {
                            Id = 65,
                            Age = 23,
                            AnnualSalary = 363699.48m,
                            Name = "Norris Reynolds",
                            TeamId = 4
                        },
                        new
                        {
                            Id = 66,
                            Age = 28,
                            AnnualSalary = 483134.69m,
                            Name = "Evelyn Prosacco",
                            TeamId = 9
                        },
                        new
                        {
                            Id = 67,
                            Age = 37,
                            AnnualSalary = 157173.86m,
                            Name = "Leonard Breitenberg",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 68,
                            Age = 20,
                            AnnualSalary = 236565.68m,
                            Name = "Karson Rosenbaum",
                            TeamId = 3
                        },
                        new
                        {
                            Id = 69,
                            Age = 32,
                            AnnualSalary = 557036.46m,
                            Name = "Golden Conroy",
                            TeamId = 10
                        },
                        new
                        {
                            Id = 70,
                            Age = 24,
                            AnnualSalary = 119832.82m,
                            Name = "Constance Harvey",
                            TeamId = 7
                        },
                        new
                        {
                            Id = 71,
                            Age = 38,
                            AnnualSalary = 920107.86m,
                            Name = "Kevon Hagenes",
                            TeamId = 6
                        },
                        new
                        {
                            Id = 72,
                            Age = 37,
                            AnnualSalary = 83393.05m,
                            Name = "Madie Wilkinson",
                            TeamId = 8
                        },
                        new
                        {
                            Id = 73,
                            Age = 25,
                            AnnualSalary = 144686.90m,
                            Name = "Cleve Kuhic",
                            TeamId = 7
                        },
                        new
                        {
                            Id = 74,
                            Age = 21,
                            AnnualSalary = 951996.50m,
                            Name = "Heaven Runte",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 75,
                            Age = 40,
                            AnnualSalary = 667904.45m,
                            Name = "Madisyn Swaniawski",
                            TeamId = 7
                        },
                        new
                        {
                            Id = 76,
                            Age = 21,
                            AnnualSalary = 184522.51m,
                            Name = "Jacynthe Aufderhar",
                            TeamId = 2
                        },
                        new
                        {
                            Id = 77,
                            Age = 23,
                            AnnualSalary = 999162.16m,
                            Name = "Yvonne Berge",
                            TeamId = 3
                        },
                        new
                        {
                            Id = 78,
                            Age = 26,
                            AnnualSalary = 683184.08m,
                            Name = "Felipa Jerde",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 79,
                            Age = 29,
                            AnnualSalary = 155925.26m,
                            Name = "Malachi Thiel",
                            TeamId = 3
                        },
                        new
                        {
                            Id = 80,
                            Age = 23,
                            AnnualSalary = 258115.61m,
                            Name = "Ewell Schuster",
                            TeamId = 6
                        },
                        new
                        {
                            Id = 81,
                            Age = 26,
                            AnnualSalary = 341101.63m,
                            Name = "Madison Johnson",
                            TeamId = 10
                        },
                        new
                        {
                            Id = 82,
                            Age = 40,
                            AnnualSalary = 707777.42m,
                            Name = "Hugh Luettgen",
                            TeamId = 3
                        },
                        new
                        {
                            Id = 83,
                            Age = 39,
                            AnnualSalary = 616625.31m,
                            Name = "Erling Toy",
                            TeamId = 4
                        },
                        new
                        {
                            Id = 84,
                            Age = 33,
                            AnnualSalary = 330232.24m,
                            Name = "Dane Bergstrom",
                            TeamId = 8
                        },
                        new
                        {
                            Id = 85,
                            Age = 22,
                            AnnualSalary = 252404.89m,
                            Name = "Meda Collier",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 86,
                            Age = 38,
                            AnnualSalary = 225436.60m,
                            Name = "Ford Abbott",
                            TeamId = 10
                        },
                        new
                        {
                            Id = 87,
                            Age = 34,
                            AnnualSalary = 444789.55m,
                            Name = "Sasha Jacobs",
                            TeamId = 5
                        },
                        new
                        {
                            Id = 88,
                            Age = 26,
                            AnnualSalary = 305564.93m,
                            Name = "Rosanna Runolfsdottir",
                            TeamId = 3
                        },
                        new
                        {
                            Id = 89,
                            Age = 31,
                            AnnualSalary = 484030.70m,
                            Name = "Samson Jenkins",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 90,
                            Age = 31,
                            AnnualSalary = 756407.31m,
                            Name = "Hoyt Bednar",
                            TeamId = 8
                        },
                        new
                        {
                            Id = 91,
                            Age = 32,
                            AnnualSalary = 470281.84m,
                            Name = "Krista Moore",
                            TeamId = 10
                        },
                        new
                        {
                            Id = 92,
                            Age = 31,
                            AnnualSalary = 256046.71m,
                            Name = "Lavern Wehner",
                            TeamId = 4
                        },
                        new
                        {
                            Id = 93,
                            Age = 33,
                            AnnualSalary = 736035.83m,
                            Name = "Abbie Treutel",
                            TeamId = 3
                        },
                        new
                        {
                            Id = 94,
                            Age = 18,
                            AnnualSalary = 219433.41m,
                            Name = "Leonie Rath",
                            TeamId = 7
                        },
                        new
                        {
                            Id = 95,
                            Age = 33,
                            AnnualSalary = 775331.98m,
                            Name = "Shemar Donnelly",
                            TeamId = 5
                        },
                        new
                        {
                            Id = 96,
                            Age = 31,
                            AnnualSalary = 484520.25m,
                            Name = "Felicia Schaefer",
                            TeamId = 2
                        },
                        new
                        {
                            Id = 97,
                            Age = 26,
                            AnnualSalary = 826847.42m,
                            Name = "Valentin Balistreri",
                            TeamId = 9
                        },
                        new
                        {
                            Id = 98,
                            Age = 18,
                            AnnualSalary = 520961.80m,
                            Name = "Natalia Reynolds",
                            TeamId = 4
                        },
                        new
                        {
                            Id = 99,
                            Age = 21,
                            AnnualSalary = 867603.73m,
                            Name = "Orrin Cummings",
                            TeamId = 2
                        },
                        new
                        {
                            Id = 100,
                            Age = 24,
                            AnnualSalary = 343424.14m,
                            Name = "Otilia Kreiger",
                            TeamId = 3
                        },
                        new
                        {
                            Id = 101,
                            Age = 27,
                            AnnualSalary = 806270.53m,
                            Name = "Bernie Gislason",
                            TeamId = 7
                        },
                        new
                        {
                            Id = 102,
                            Age = 29,
                            AnnualSalary = 699645.57m,
                            Name = "Anabelle Stokes",
                            TeamId = 3
                        },
                        new
                        {
                            Id = 103,
                            Age = 24,
                            AnnualSalary = 704946.35m,
                            Name = "Brennon Kihn",
                            TeamId = 2
                        },
                        new
                        {
                            Id = 104,
                            Age = 23,
                            AnnualSalary = 780446.35m,
                            Name = "Meda Lang",
                            TeamId = 6
                        },
                        new
                        {
                            Id = 105,
                            Age = 32,
                            AnnualSalary = 689817.67m,
                            Name = "Kylee Considine",
                            TeamId = 4
                        },
                        new
                        {
                            Id = 106,
                            Age = 18,
                            AnnualSalary = 761552.66m,
                            Name = "Rico Cummings",
                            TeamId = 3
                        },
                        new
                        {
                            Id = 107,
                            Age = 36,
                            AnnualSalary = 520730.40m,
                            Name = "Maria Bode",
                            TeamId = 7
                        },
                        new
                        {
                            Id = 108,
                            Age = 39,
                            AnnualSalary = 48248.68m,
                            Name = "Rupert Lesch",
                            TeamId = 5
                        },
                        new
                        {
                            Id = 109,
                            Age = 33,
                            AnnualSalary = 56549.22m,
                            Name = "Elinor O'Kon",
                            TeamId = 9
                        },
                        new
                        {
                            Id = 110,
                            Age = 36,
                            AnnualSalary = 518248.15m,
                            Name = "Joseph Lynch",
                            TeamId = 2
                        });
                });

            modelBuilder.Entity("NetCoreGraphQlLearn.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("LeagueId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TeamColors")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("iconLink")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LeagueId");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LeagueId = 1,
                            Name = "Gulgowski and Sons",
                            TeamColors = "ivory",
                            iconLink = "https://raegan.org"
                        },
                        new
                        {
                            Id = 2,
                            LeagueId = 1,
                            Name = "Morissette, MacGyver and Bins",
                            TeamColors = "green",
                            iconLink = "https://dave.org"
                        },
                        new
                        {
                            Id = 3,
                            LeagueId = 3,
                            Name = "Schiller, Witting and Herzog",
                            TeamColors = "violet",
                            iconLink = "http://myrl.biz"
                        },
                        new
                        {
                            Id = 4,
                            LeagueId = 3,
                            Name = "Daniel Group",
                            TeamColors = "white",
                            iconLink = "https://rogelio.com"
                        },
                        new
                        {
                            Id = 5,
                            LeagueId = 2,
                            Name = "Hauck - Boyer",
                            TeamColors = "maroon",
                            iconLink = "https://ruthe.info"
                        },
                        new
                        {
                            Id = 6,
                            LeagueId = 3,
                            Name = "Abshire, Bernhard and Murphy",
                            TeamColors = "lime",
                            iconLink = "https://jordi.info"
                        },
                        new
                        {
                            Id = 7,
                            LeagueId = 2,
                            Name = "Aufderhar - Yost",
                            TeamColors = "blue",
                            iconLink = "https://cortney.info"
                        },
                        new
                        {
                            Id = 8,
                            LeagueId = 5,
                            Name = "Smith, Kerluke and Senger",
                            TeamColors = "plum",
                            iconLink = "https://hilton.net"
                        },
                        new
                        {
                            Id = 9,
                            LeagueId = 2,
                            Name = "Nader - Nolan",
                            TeamColors = "red",
                            iconLink = "http://ızaiah.biz"
                        },
                        new
                        {
                            Id = 10,
                            LeagueId = 1,
                            Name = "King - Collier",
                            TeamColors = "yellow",
                            iconLink = "https://lew.net"
                        });
                });

            modelBuilder.Entity("NetCoreGraphQlLearn.Models.Player", b =>
                {
                    b.HasOne("NetCoreGraphQlLearn.Models.Team", "Team")
                        .WithMany("Players")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("NetCoreGraphQlLearn.Models.Team", b =>
                {
                    b.HasOne("NetCoreGraphQlLearn.Models.League", "League")
                        .WithMany("Teams")
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("League");
                });

            modelBuilder.Entity("NetCoreGraphQlLearn.Models.League", b =>
                {
                    b.Navigation("Teams");
                });

            modelBuilder.Entity("NetCoreGraphQlLearn.Models.Team", b =>
                {
                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
