// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetCoreGraphQlLearn.Database;

#nullable disable

namespace NetCoreGraphQlLearn.Migrations
{
    [DbContext(typeof(AppDb))]
    [Migration("20230711163522_InitMig")]
    partial class InitMig
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NetCoreGraphQlLearn.Models.League", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("flagLink")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Leagues");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Wuckert LLC",
                            flagLink = "http://myron.com"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Brakus and Sons",
                            flagLink = "https://braxton.org"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Welch LLC",
                            flagLink = "http://reagan.biz"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Bednar - Treutel",
                            flagLink = "https://erika.net"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Langworth, Schuster and Walsh",
                            flagLink = "https://ubaldo.info"
                        });
                });

            modelBuilder.Entity("NetCoreGraphQlLearn.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<decimal>("AnnualSalary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 39,
                            AnnualSalary = 135930.04m,
                            Name = "Lonzo Gulgowski",
                            TeamId = 4
                        },
                        new
                        {
                            Id = 2,
                            Age = 31,
                            AnnualSalary = 75212.67m,
                            Name = "Michele Howe",
                            TeamId = 10
                        },
                        new
                        {
                            Id = 3,
                            Age = 22,
                            AnnualSalary = 120418.99m,
                            Name = "Nola Morar",
                            TeamId = 9
                        },
                        new
                        {
                            Id = 4,
                            Age = 25,
                            AnnualSalary = 445334.63m,
                            Name = "Eliane Romaguera",
                            TeamId = 3
                        },
                        new
                        {
                            Id = 5,
                            Age = 29,
                            AnnualSalary = 36625.24m,
                            Name = "Lenore Torp",
                            TeamId = 8
                        },
                        new
                        {
                            Id = 6,
                            Age = 20,
                            AnnualSalary = 319467.42m,
                            Name = "Nicolas Brekke",
                            TeamId = 3
                        },
                        new
                        {
                            Id = 7,
                            Age = 32,
                            AnnualSalary = 123749.40m,
                            Name = "Rebecca Klocko",
                            TeamId = 10
                        },
                        new
                        {
                            Id = 8,
                            Age = 27,
                            AnnualSalary = 44103.98m,
                            Name = "Maximus Reynolds",
                            TeamId = 3
                        },
                        new
                        {
                            Id = 9,
                            Age = 25,
                            AnnualSalary = 89114.17m,
                            Name = "Cydney Farrell",
                            TeamId = 8
                        },
                        new
                        {
                            Id = 10,
                            Age = 33,
                            AnnualSalary = 821768.78m,
                            Name = "Jordi Marquardt",
                            TeamId = 7
                        },
                        new
                        {
                            Id = 11,
                            Age = 25,
                            AnnualSalary = 570665.10m,
                            Name = "Katheryn Kessler",
                            TeamId = 9
                        },
                        new
                        {
                            Id = 12,
                            Age = 37,
                            AnnualSalary = 236422.66m,
                            Name = "Adaline Frami",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 13,
                            Age = 25,
                            AnnualSalary = 590969.91m,
                            Name = "Jedidiah Shanahan",
                            TeamId = 2
                        },
                        new
                        {
                            Id = 14,
                            Age = 23,
                            AnnualSalary = 843401.59m,
                            Name = "Janis Gutkowski",
                            TeamId = 6
                        },
                        new
                        {
                            Id = 15,
                            Age = 36,
                            AnnualSalary = 154799.62m,
                            Name = "Otto Hodkiewicz",
                            TeamId = 4
                        },
                        new
                        {
                            Id = 16,
                            Age = 23,
                            AnnualSalary = 606353.01m,
                            Name = "Deven Nader",
                            TeamId = 5
                        },
                        new
                        {
                            Id = 17,
                            Age = 23,
                            AnnualSalary = 350107.50m,
                            Name = "Milton Renner",
                            TeamId = 7
                        },
                        new
                        {
                            Id = 18,
                            Age = 30,
                            AnnualSalary = 914965.73m,
                            Name = "Maurice Heller",
                            TeamId = 7
                        },
                        new
                        {
                            Id = 19,
                            Age = 36,
                            AnnualSalary = 756228.77m,
                            Name = "Sylvia Kling",
                            TeamId = 6
                        },
                        new
                        {
                            Id = 20,
                            Age = 24,
                            AnnualSalary = 991968.23m,
                            Name = "Arvilla Kris",
                            TeamId = 8
                        },
                        new
                        {
                            Id = 21,
                            Age = 26,
                            AnnualSalary = 285462.05m,
                            Name = "Brandt Kiehn",
                            TeamId = 4
                        },
                        new
                        {
                            Id = 22,
                            Age = 27,
                            AnnualSalary = 33731.33m,
                            Name = "Arvilla Green",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 23,
                            Age = 31,
                            AnnualSalary = 852796.06m,
                            Name = "Selina Beatty",
                            TeamId = 4
                        },
                        new
                        {
                            Id = 24,
                            Age = 18,
                            AnnualSalary = 751994.95m,
                            Name = "Paris Wilderman",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 25,
                            Age = 31,
                            AnnualSalary = 649572.01m,
                            Name = "Elouise Quigley",
                            TeamId = 2
                        },
                        new
                        {
                            Id = 26,
                            Age = 34,
                            AnnualSalary = 847645.78m,
                            Name = "Ezra Williamson",
                            TeamId = 7
                        },
                        new
                        {
                            Id = 27,
                            Age = 36,
                            AnnualSalary = 563832.03m,
                            Name = "Oswald Kuphal",
                            TeamId = 5
                        },
                        new
                        {
                            Id = 28,
                            Age = 29,
                            AnnualSalary = 915917.11m,
                            Name = "Otto Corwin",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 29,
                            Age = 31,
                            AnnualSalary = 673738.93m,
                            Name = "Althea Erdman",
                            TeamId = 10
                        },
                        new
                        {
                            Id = 30,
                            Age = 40,
                            AnnualSalary = 486513.01m,
                            Name = "Eduardo Lind",
                            TeamId = 9
                        },
                        new
                        {
                            Id = 31,
                            Age = 26,
                            AnnualSalary = 320736.81m,
                            Name = "Evelyn Leannon",
                            TeamId = 8
                        },
                        new
                        {
                            Id = 32,
                            Age = 25,
                            AnnualSalary = 455243.05m,
                            Name = "Lelia Hansen",
                            TeamId = 6
                        },
                        new
                        {
                            Id = 33,
                            Age = 38,
                            AnnualSalary = 536447.07m,
                            Name = "Golda Harris",
                            TeamId = 4
                        },
                        new
                        {
                            Id = 34,
                            Age = 28,
                            AnnualSalary = 422638.54m,
                            Name = "Brittany Thompson",
                            TeamId = 8
                        },
                        new
                        {
                            Id = 35,
                            Age = 36,
                            AnnualSalary = 452328.04m,
                            Name = "Kristy Kertzmann",
                            TeamId = 6
                        },
                        new
                        {
                            Id = 36,
                            Age = 39,
                            AnnualSalary = 268881.80m,
                            Name = "Wilson Beier",
                            TeamId = 4
                        },
                        new
                        {
                            Id = 37,
                            Age = 19,
                            AnnualSalary = 549301.74m,
                            Name = "Jessica Howell",
                            TeamId = 6
                        },
                        new
                        {
                            Id = 38,
                            Age = 35,
                            AnnualSalary = 721489.28m,
                            Name = "Loy Kertzmann",
                            TeamId = 8
                        },
                        new
                        {
                            Id = 39,
                            Age = 20,
                            AnnualSalary = 673195.69m,
                            Name = "Trace Klocko",
                            TeamId = 10
                        },
                        new
                        {
                            Id = 40,
                            Age = 25,
                            AnnualSalary = 288553.98m,
                            Name = "Alvina Schaefer",
                            TeamId = 6
                        },
                        new
                        {
                            Id = 41,
                            Age = 28,
                            AnnualSalary = 552871.15m,
                            Name = "Nona Walsh",
                            TeamId = 9
                        },
                        new
                        {
                            Id = 42,
                            Age = 26,
                            AnnualSalary = 545127.39m,
                            Name = "Veda Will",
                            TeamId = 2
                        },
                        new
                        {
                            Id = 43,
                            Age = 28,
                            AnnualSalary = 909887.82m,
                            Name = "Ignacio Torp",
                            TeamId = 10
                        },
                        new
                        {
                            Id = 44,
                            Age = 22,
                            AnnualSalary = 730425.41m,
                            Name = "Katelyn Schoen",
                            TeamId = 3
                        },
                        new
                        {
                            Id = 45,
                            Age = 32,
                            AnnualSalary = 888243.39m,
                            Name = "Elinor Goodwin",
                            TeamId = 4
                        },
                        new
                        {
                            Id = 46,
                            Age = 32,
                            AnnualSalary = 600528.53m,
                            Name = "Esta Schowalter",
                            TeamId = 9
                        },
                        new
                        {
                            Id = 47,
                            Age = 27,
                            AnnualSalary = 898016.01m,
                            Name = "Velda Heidenreich",
                            TeamId = 8
                        },
                        new
                        {
                            Id = 48,
                            Age = 22,
                            AnnualSalary = 13075.89m,
                            Name = "Ahmad Harvey",
                            TeamId = 10
                        },
                        new
                        {
                            Id = 49,
                            Age = 30,
                            AnnualSalary = 801742.18m,
                            Name = "Jimmy Pfannerstill",
                            TeamId = 4
                        },
                        new
                        {
                            Id = 50,
                            Age = 24,
                            AnnualSalary = 577492.74m,
                            Name = "Ladarius Volkman",
                            TeamId = 2
                        },
                        new
                        {
                            Id = 51,
                            Age = 23,
                            AnnualSalary = 419049.84m,
                            Name = "Orland Kemmer",
                            TeamId = 8
                        },
                        new
                        {
                            Id = 52,
                            Age = 26,
                            AnnualSalary = 473062.53m,
                            Name = "Mable Quitzon",
                            TeamId = 8
                        },
                        new
                        {
                            Id = 53,
                            Age = 33,
                            AnnualSalary = 21520.99m,
                            Name = "Ivah Friesen",
                            TeamId = 4
                        },
                        new
                        {
                            Id = 54,
                            Age = 34,
                            AnnualSalary = 425507.11m,
                            Name = "Earlene Pouros",
                            TeamId = 4
                        },
                        new
                        {
                            Id = 55,
                            Age = 29,
                            AnnualSalary = 536860.54m,
                            Name = "Ottilie Steuber",
                            TeamId = 3
                        },
                        new
                        {
                            Id = 56,
                            Age = 30,
                            AnnualSalary = 996274.70m,
                            Name = "Angie Bayer",
                            TeamId = 7
                        },
                        new
                        {
                            Id = 57,
                            Age = 19,
                            AnnualSalary = 446098.17m,
                            Name = "Theodora Kris",
                            TeamId = 5
                        },
                        new
                        {
                            Id = 58,
                            Age = 33,
                            AnnualSalary = 175818.76m,
                            Name = "Dante Miller",
                            TeamId = 7
                        },
                        new
                        {
                            Id = 59,
                            Age = 18,
                            AnnualSalary = 797863.92m,
                            Name = "Rupert Stark",
                            TeamId = 10
                        },
                        new
                        {
                            Id = 60,
                            Age = 30,
                            AnnualSalary = 124998.65m,
                            Name = "Carole Wintheiser",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 61,
                            Age = 19,
                            AnnualSalary = 270461.46m,
                            Name = "Van Von",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 62,
                            Age = 18,
                            AnnualSalary = 269548.37m,
                            Name = "Bell Mayer",
                            TeamId = 9
                        },
                        new
                        {
                            Id = 63,
                            Age = 39,
                            AnnualSalary = 654299.50m,
                            Name = "Werner Schoen",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 64,
                            Age = 18,
                            AnnualSalary = 642781.84m,
                            Name = "Alexandra Leffler",
                            TeamId = 7
                        },
                        new
                        {
                            Id = 65,
                            Age = 34,
                            AnnualSalary = 365080.65m,
                            Name = "Maria Padberg",
                            TeamId = 5
                        },
                        new
                        {
                            Id = 66,
                            Age = 36,
                            AnnualSalary = 373210.26m,
                            Name = "Felicia Balistreri",
                            TeamId = 10
                        },
                        new
                        {
                            Id = 67,
                            Age = 39,
                            AnnualSalary = 834113.58m,
                            Name = "Meaghan Pfannerstill",
                            TeamId = 8
                        },
                        new
                        {
                            Id = 68,
                            Age = 33,
                            AnnualSalary = 42052.76m,
                            Name = "Kyler Smitham",
                            TeamId = 9
                        },
                        new
                        {
                            Id = 69,
                            Age = 32,
                            AnnualSalary = 809973.47m,
                            Name = "John Monahan",
                            TeamId = 2
                        },
                        new
                        {
                            Id = 70,
                            Age = 25,
                            AnnualSalary = 401941.05m,
                            Name = "Garland Dach",
                            TeamId = 2
                        },
                        new
                        {
                            Id = 71,
                            Age = 38,
                            AnnualSalary = 369348.22m,
                            Name = "Samara Jacobson",
                            TeamId = 3
                        },
                        new
                        {
                            Id = 72,
                            Age = 24,
                            AnnualSalary = 826744.20m,
                            Name = "Timothy Bartell",
                            TeamId = 4
                        },
                        new
                        {
                            Id = 73,
                            Age = 30,
                            AnnualSalary = 629824.94m,
                            Name = "Naomi Smith",
                            TeamId = 4
                        },
                        new
                        {
                            Id = 74,
                            Age = 22,
                            AnnualSalary = 642402.45m,
                            Name = "Kennith Thiel",
                            TeamId = 5
                        },
                        new
                        {
                            Id = 75,
                            Age = 26,
                            AnnualSalary = 112986.65m,
                            Name = "Glen Witting",
                            TeamId = 7
                        },
                        new
                        {
                            Id = 76,
                            Age = 31,
                            AnnualSalary = 56271.44m,
                            Name = "Jaida Jakubowski",
                            TeamId = 5
                        },
                        new
                        {
                            Id = 77,
                            Age = 33,
                            AnnualSalary = 637701.75m,
                            Name = "Niko Braun",
                            TeamId = 5
                        },
                        new
                        {
                            Id = 78,
                            Age = 33,
                            AnnualSalary = 925060.65m,
                            Name = "Reginald Nienow",
                            TeamId = 3
                        },
                        new
                        {
                            Id = 79,
                            Age = 36,
                            AnnualSalary = 37707.45m,
                            Name = "Annie Champlin",
                            TeamId = 2
                        },
                        new
                        {
                            Id = 80,
                            Age = 25,
                            AnnualSalary = 172467.28m,
                            Name = "Greg Larson",
                            TeamId = 9
                        },
                        new
                        {
                            Id = 81,
                            Age = 39,
                            AnnualSalary = 626894.63m,
                            Name = "Stefan Leffler",
                            TeamId = 4
                        },
                        new
                        {
                            Id = 82,
                            Age = 38,
                            AnnualSalary = 783893.03m,
                            Name = "Krystal Miller",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 83,
                            Age = 32,
                            AnnualSalary = 925320.96m,
                            Name = "Lonie Thompson",
                            TeamId = 2
                        },
                        new
                        {
                            Id = 84,
                            Age = 30,
                            AnnualSalary = 839860.18m,
                            Name = "Noe Lesch",
                            TeamId = 4
                        },
                        new
                        {
                            Id = 85,
                            Age = 39,
                            AnnualSalary = 189779.85m,
                            Name = "Abdul Wunsch",
                            TeamId = 7
                        },
                        new
                        {
                            Id = 86,
                            Age = 34,
                            AnnualSalary = 106924.44m,
                            Name = "Jaeden Jakubowski",
                            TeamId = 7
                        },
                        new
                        {
                            Id = 87,
                            Age = 27,
                            AnnualSalary = 116605.57m,
                            Name = "Kacie West",
                            TeamId = 10
                        },
                        new
                        {
                            Id = 88,
                            Age = 35,
                            AnnualSalary = 933709.58m,
                            Name = "Janice Baumbach",
                            TeamId = 10
                        },
                        new
                        {
                            Id = 89,
                            Age = 30,
                            AnnualSalary = 603156.48m,
                            Name = "Kaci Morar",
                            TeamId = 2
                        },
                        new
                        {
                            Id = 90,
                            Age = 26,
                            AnnualSalary = 183416.08m,
                            Name = "Josephine Jakubowski",
                            TeamId = 10
                        },
                        new
                        {
                            Id = 91,
                            Age = 25,
                            AnnualSalary = 663244.42m,
                            Name = "Cristobal Pagac",
                            TeamId = 9
                        },
                        new
                        {
                            Id = 92,
                            Age = 36,
                            AnnualSalary = 795143.48m,
                            Name = "Viola Towne",
                            TeamId = 6
                        },
                        new
                        {
                            Id = 93,
                            Age = 36,
                            AnnualSalary = 519280.80m,
                            Name = "Merlin Hermiston",
                            TeamId = 2
                        },
                        new
                        {
                            Id = 94,
                            Age = 32,
                            AnnualSalary = 509735.46m,
                            Name = "Shaylee Wisoky",
                            TeamId = 9
                        },
                        new
                        {
                            Id = 95,
                            Age = 39,
                            AnnualSalary = 406623.97m,
                            Name = "Boris Jacobs",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 96,
                            Age = 32,
                            AnnualSalary = 67877.65m,
                            Name = "Jane Lind",
                            TeamId = 9
                        },
                        new
                        {
                            Id = 97,
                            Age = 23,
                            AnnualSalary = 43694.09m,
                            Name = "Unique Ziemann",
                            TeamId = 3
                        },
                        new
                        {
                            Id = 98,
                            Age = 39,
                            AnnualSalary = 86904.63m,
                            Name = "Monserrat Kutch",
                            TeamId = 8
                        },
                        new
                        {
                            Id = 99,
                            Age = 35,
                            AnnualSalary = 720466.54m,
                            Name = "Lorenz Kessler",
                            TeamId = 3
                        },
                        new
                        {
                            Id = 100,
                            Age = 19,
                            AnnualSalary = 347597.91m,
                            Name = "Chanel McCullough",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 101,
                            Age = 32,
                            AnnualSalary = 312506.37m,
                            Name = "Bethany Upton",
                            TeamId = 6
                        },
                        new
                        {
                            Id = 102,
                            Age = 30,
                            AnnualSalary = 816280.84m,
                            Name = "Isidro Dickinson",
                            TeamId = 6
                        },
                        new
                        {
                            Id = 103,
                            Age = 24,
                            AnnualSalary = 599540.20m,
                            Name = "Rowan Fisher",
                            TeamId = 7
                        },
                        new
                        {
                            Id = 104,
                            Age = 30,
                            AnnualSalary = 173845.96m,
                            Name = "Elvie Goldner",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 105,
                            Age = 40,
                            AnnualSalary = 593461.66m,
                            Name = "Ashtyn Graham",
                            TeamId = 3
                        },
                        new
                        {
                            Id = 106,
                            Age = 39,
                            AnnualSalary = 693060.09m,
                            Name = "Virginie Funk",
                            TeamId = 8
                        },
                        new
                        {
                            Id = 107,
                            Age = 33,
                            AnnualSalary = 277944.69m,
                            Name = "Gregory Konopelski",
                            TeamId = 10
                        },
                        new
                        {
                            Id = 108,
                            Age = 29,
                            AnnualSalary = 422648.94m,
                            Name = "Madilyn Rath",
                            TeamId = 10
                        },
                        new
                        {
                            Id = 109,
                            Age = 36,
                            AnnualSalary = 708490.65m,
                            Name = "Kraig Hegmann",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 110,
                            Age = 29,
                            AnnualSalary = 588396.55m,
                            Name = "Connie Jaskolski",
                            TeamId = 6
                        });
                });

            modelBuilder.Entity("NetCoreGraphQlLearn.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("LeagueId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TeamColors")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("iconLink")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LeagueId");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LeagueId = 2,
                            Name = "Hartmann and Sons",
                            TeamColors = "salmon",
                            iconLink = "http://daphnee.name"
                        },
                        new
                        {
                            Id = 2,
                            LeagueId = 4,
                            Name = "Harris, Stiedemann and Lang",
                            TeamColors = "grey",
                            iconLink = "http://alejandra.name"
                        },
                        new
                        {
                            Id = 3,
                            LeagueId = 5,
                            Name = "Reinger Inc",
                            TeamColors = "plum",
                            iconLink = "http://eleonore.com"
                        },
                        new
                        {
                            Id = 4,
                            LeagueId = 2,
                            Name = "Leannon - Morar",
                            TeamColors = "violet",
                            iconLink = "https://reva.info"
                        },
                        new
                        {
                            Id = 5,
                            LeagueId = 2,
                            Name = "Greenholt Group",
                            TeamColors = "black",
                            iconLink = "https://austin.biz"
                        },
                        new
                        {
                            Id = 6,
                            LeagueId = 4,
                            Name = "Larkin LLC",
                            TeamColors = "white",
                            iconLink = "http://brooks.org"
                        },
                        new
                        {
                            Id = 7,
                            LeagueId = 3,
                            Name = "Cole - Feest",
                            TeamColors = "gold",
                            iconLink = "https://nat.org"
                        },
                        new
                        {
                            Id = 8,
                            LeagueId = 1,
                            Name = "Beahan Inc",
                            TeamColors = "sky blue",
                            iconLink = "https://rudy.net"
                        },
                        new
                        {
                            Id = 9,
                            LeagueId = 5,
                            Name = "Crona, Ankunding and Kessler",
                            TeamColors = "white",
                            iconLink = "http://libbie.biz"
                        },
                        new
                        {
                            Id = 10,
                            LeagueId = 3,
                            Name = "Haley, Jacobs and Kiehn",
                            TeamColors = "tan",
                            iconLink = "https://ınes.name"
                        });
                });

            modelBuilder.Entity("NetCoreGraphQlLearn.Models.Player", b =>
                {
                    b.HasOne("NetCoreGraphQlLearn.Models.Team", "Team")
                        .WithMany("Players")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("NetCoreGraphQlLearn.Models.Team", b =>
                {
                    b.HasOne("NetCoreGraphQlLearn.Models.League", "League")
                        .WithMany("Teams")
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("League");
                });

            modelBuilder.Entity("NetCoreGraphQlLearn.Models.League", b =>
                {
                    b.Navigation("Teams");
                });

            modelBuilder.Entity("NetCoreGraphQlLearn.Models.Team", b =>
                {
                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
